/*
 * Invitations.
 */

// Fetch.
export const FETCH_INVITATIONS = 'FETCH_INVITATIONS';
export const FETCH_INVITATIONS_INIT = 'FETCH_INVITATIONS_INIT';
export const FETCH_INVITATIONS_REJECTED = 'FETCH_INVITATIONS_REJECTED';
export const FETCH_INVITATIONS_FULFILLED = 'FETCH_INVITATIONS_FULFILLED';

// Invite User.
export const INVITE_USER = 'INVITE_USER';
export const INVITE_USER_PENDING = 'INVITE_USER_PENDING';
export const INVITE_USER_REJECTED = 'INVITE_USER_REJECTED';
export const INVITE_USER_FULFILLED = 'INVITE_USER_FULFILLED';

// Connections.
export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS';
export const FETCH_CONNECTIONS_PENDING = 'FETCH_CONNECTIONS_PENDING';
export const FETCH_CONNECTIONS_REJECTED = 'FETCH_CONNECTIONS_REJECTED';
export const FETCH_CONNECTIONS_FULFILLED = 'FETCH_CONNECTIONS_FULFILLED';

/*
 * Auth.
 */

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
